# -*- coding: utf-8 -*-
"""xgboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1joEBueI-CHM0GEF4ina3M7dL9D2Qfh3x
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_percentage_error

!pip install xgboost

df= pd.read_csv('data.csv')

df['timestamp']= pd.to_datetime(df['timestamp'])
df['hour']= df['timestamp'].dt.hour
df['day_of_week']= df['timestamp'].dt.dayofweek
df['month']= df['timestamp'].dt.month

df['lag_1'] = df['number_people'].shift(1)
df['lag_24'] = df['number_people'].shift(24)
df['rolling_mean_3'] = df['number_people'].rolling(window=3).mean()

df = df.dropna().reset_index(drop=True)

df = df.drop(columns = ['date','timestamp'])
features= [
    'day_of_week',
    'is_weekend',
    'is_holiday',
    'temperature',
    'is_start_of_semester',
    'is_during_semester',
    'month',
    'hour', 'lag_1', 'lag_24', 'rolling_mean_3'
]
X = df[features];
y = df.iloc[:,0]

t_split = TimeSeriesSplit(n_splits=3)
model = XGBRegressor(n_estimators=1000,learning_rate = 0.05, random_state= 42)

import os
import pickle
from sklearn.metrics import r2_score
r2hist =[]
mapehist =[]
for f,(train_idx,test_idx) in enumerate(t_split.split(y)):
  x_train,y_train = X.iloc[train_idx],y.iloc[train_idx]
  x_test,y_test = X.iloc[test_idx],y.iloc[test_idx]

  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  r2 = r2_score(y_pred,y_test)
  r2hist.append(r2)
  print(f'R2 for {f}: {r2}')
  mape= mean_absolute_percentage_error(y_test,y_pred)
  mapehist.append(mape)
  print(f'Mape for {f}: {mape}')
R2 = np.mean(r2hist)
mape = np.mean(mapehist)
rmse = np.sqrt(np.mean(np.square(y_pred - y_test)))
print(f'RMSE: {rmse}')
print(f'Mape: {mape}')
print(f'R2: {R2}')
model.fit(X,y)

with open("crowd_model.pkl", "wb") as f:
    pickle.dump(model, f)
print("Model trained and saved successfully!")

